### ISSUE TITLE
cdn not working

### ISSUE THREAD

**Issue by ZakariyaeChmaili** [tomickigrzegorz/circular-progress-bar#98]
gives 404 error when using cdn and when opening the cdn on the browser i get :
**Failed to fetch tomickigrzegorz/circular-progress-bar@1.2.4 from GitHub.**

here is the cdn that i used just in case if it change in the future :
https://cdn.jsdelivr.net/gh/tomickigrzegorz/circular-progress-bar@1.2.4/dist/circularProgressBar.min.js

**Comment by tomickigrzegorz** [comment]
Thanks for the info.
It should work now.
